### ISSUE TITLE
Cannot access PhpMyAdmin after installing, default password of mysql?

### ISSUE THREAD

**Issue by benzamin** [1and1internet/ubuntu-16-nginx-php-phpmyadmin-mysql-5#10]
Hello, I'm a noob in docker world. Good image, saves a lot of time.

I downloaded and fired up the container fine, but after that I can't access the phpmyadmin panel, need to know the root default password. I tried empty pass, that didn't work.

 I tried to reset the mysql  password by accessing the mysqld_safe, but was unable to stop mysql, it restarts once its stopped.

Please help me here.

**Comment by brianwilkinson** [comment]
Hi benzamin,

I'm glad you find the image useful. All our images have been adapted for our requirements here at 1and1 but it's nice to hear somebody else using them. If you wanted to run this particular image you might want to try something like:

docker run -it --rm -p 8080:8080 -e MYSQL_ADMIN_USER=benzamin -e MYSQL_ADMIN_PASSWORD=yourP@55 -u10000 1and1internet/ubuntu-16-nginx-php-phpmyadmin-mysql-5:latest

You can use '-u<whatever user id you like>' but these images wont typically run properly as root as we try to restrict unnecessary privileges.

I hope this helps.

Regards, Brian

**Comment by benzamin** [comment]
Thanks, I was missing the environment variables for mysql 👍
