### ISSUE TITLE
Can not restart MySql in docker

### ISSUE THREAD

**Issue by namnh06** [1and1internet/ubuntu-16-nginx-php-phpmyadmin-mysql-5#11]
Hi guys,

I'm working on this docker images. It's so good, fully and clearly.

But I have a problem, when I run the container from this image

`docker run -u 999:0 -e MYSQL_ROOT_PASSWORD='something' --name nb -p 6789:8080 -v /var/www/html/:/var/www/html/ -p 3307:3306 -v /var/lib/mysql/:/var/lib/mysql/ 1and1internet/ubuntu-16-nginx-php-phpmyadmin-mysql-5`

It worked. But MySql is not working like the way I want. I run command in docker : 

```
mysql -u root -p something
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

Then I know that I didn't restart MySql. After use 

```
service mysql restart
 * Stopping MySQL database server mysqld                                 [ OK ] 
 * Starting MySQL database server mysqld                                        Password:
```

It's not a password of mysql, it's password of docker container.

So, let me know what happen and help me out of this.

Thanks.

**Comment by brianwilkinson** [comment]
Hi

You might want to try connecting to the IP of the container. You can usually find this by using (eg) 
 > docker inspect nb

So you would more likely connect using something like
 > mysql -h 172.17.0.2 -u root -p

I hope this helps

Regards

**Comment by namnh06** [comment]
Thanks @brianwilkinson 

I solved my problem, it's can not connect to host mysql, so i decided move -v /var/lib/mysql to /var/lib/mysql/docker.

It works.
